# Generated by Django 2.2.6 on 2019-11-05 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Ropa',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=120)),
                ('pvp', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pfinal', models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, max_digits=7), max_digits=7)),
                ('categoria', models.CharField(max_length=120)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIndiTDE.Marca')),
            ],
        ),
    ]
