# Generated by Django 2.2.6 on 2019-11-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIndiTDE', '0002_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='lista_deseo',
            field=models.ManyToManyField(related_name='id232323', to='appIndiTDE.Ropa'),
        ),
    ]
