# Generated by Django 2.2.6 on 2019-11-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIndiTDE', '0003_usuario_lista_deseo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='lista_deseo',
            field=models.ManyToManyField(related_name='lista_deseo', to='appIndiTDE.Ropa'),
        ),
    ]
