# Generated by Django 2.2.6 on 2019-11-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIndiTDE', '0004_auto_20191105_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='ropa',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'FEMENINO'), ('unisex', 'UNISEX')], default='unisex', max_length=10),
        ),
    ]
