# Generated by Django 2.2.6 on 2019-11-15 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appIndiTDE', '0005_ropa_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('texto', models.CharField(max_length=240)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIndiTDE.Usuario')),
            ],
        ),
    ]
