# Generated by Django 2.2.6 on 2019-11-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIndiTDE', '0007_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='Valoracion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
