# Generated by Django 2.2.6 on 2019-11-16 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appIndiTDE', '0008_comentario_valoracion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='Valoracion',
            new_name='valoracion',
        ),
    ]
