# Generated by Django 2.2.6 on 2019-11-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIndiTDE', '0009_auto_20191116_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugerencia',
            name='autor',
            field=models.CharField(max_length=30),
        ),
    ]
