# Generated by Django 2.2.6 on 2019-11-16 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appIndiTDE', '0010_auto_20191116_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugerencia',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIndiTDE.Usuario'),
        ),
    ]
