# Generated by Django 2.2.6 on 2019-12-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIndiTDE', '0013_carro'),
    ]

    operations = [
        migrations.AddField(
            model_name='ropa',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
