# Generated by Django 2.2.8 on 2019-12-20 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appIndiTDE', '0015_marca_descen'),
        ('appIndiTDE', '0015_favorito'),
    ]

    operations = [
    ]
